import GeneralizationLinter.Basic
import GeneralizationLinter.Helpers.Digraph
import GeneralizationLinter.Helpers.ClassDag
import GeneralizationLinter.Helpers.Canonicalization
import GeneralizationLinter.Helpers.ClassApp
