import GeneralizationLinter.Basic
import GeneralizationLinter.Core.Linter
import GeneralizationLinter.Core.Options
import GeneralizationLinter.Helpers.Coalescence
import GeneralizationLinter.Helpers.Digraph
import GeneralizationLinter.Helpers.ClassGraph
import GeneralizationLinter.Helpers.Canonicalization
import GeneralizationLinter.Helpers.Vertex
