name: Build project and docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build project
        uses: leanprover/lean-action@v1

      - name: Generate documentstion
        uses: leanprover-community/docgen-action@main
